apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: my-tgb
  namespace: ui
spec:
  targetType: ip
  serviceRef:
    name: ui # route traffic to the ui-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:003128362271:targetgroup/tg-blue-ui/e60d5d6a0bf854f0